name: refresh-data
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/15 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Data
        run: |
          curl -sLw '\n' \
          --request POST \
          --url 'https://stacksstatus.vercel.app/api/refresh' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
